//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class My : global::System.Configuration.ApplicationSettingsBase {
        
        private static My defaultInstance = ((My)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new My())));
        
        public static My Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string Setting01 {
            get {
                return ((string)(this["Setting01"]));
            }
            set {
                this["Setting01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02")]
        public string Setting02 {
            get {
                return ((string)(this["Setting02NewNewNew"]));
            }
            set {
                this["Setting02NewNewNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03")]
        public string Setting03 {
            get {
                return ((string)(this["MySetting03New"]));
            }
            set {
                this["MySetting03New"] = value;
            }
        }
    }
}
